using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjectFarmerAPI.Models
{
    /// <summary>
    /// The Farmer Class
    /// </summary>
    public class Farmer
    {
        /// <summary>
        /// The Farmers Id. (It will be generated by back-end)
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// The Farmers First Name
        /// </summary>
        [Required]
        public string FirstName { get; set; }

        /// <summary>
        /// The Farmers Last Name
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        /// The Date Of Birth of the Farmer
        /// </summary>
        [Required]
        public DateTime DOB { get; set; }

        /// <summary>
        /// The Mobile Number of the Farmer, it can be different from the address. We can use this same number for the Address as well.
        /// </summary>
        [Required]
        public string MobileNumber { get; set; }

        /// <summary>
        /// The Secondary Phone Number
        /// </summary>
        public string PhoneNumber { get; set; }

        /// <summary>
        /// The Prefered Address of the Farmer  
        /// </summary>
        [Required]
        public Address PreferedAddress { get; set; }

        /// <summary>
        /// The Other Addresses of the Farmer, null in case of no other address
        /// </summary>
        public IEnumerable<Address> Addresses { get; set; }

        /// <summary>
        /// This is very private information about the Farmer and it will not be accesable by outsiders
        /// </summary>
        protected double FarmerRating { get; private set; }

        /// <summary>
        /// The List of Items Farmer has
        /// </summary>
        public IDictionary<int, double> FarmerItems { get; set; }
    }
}