using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjectFarmerAPI.Models
{
    public class Rating
    {
        /// <summary>
        /// The Id, Generated by the back end.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// The Rating which can varry from 1 being worst to 5 being very good
        /// </summary>
        [Required]
        public int Rate { get; set; }

        /// <summary>
        /// The users custom comment
        /// </summary>
        public string Comments { get; set; }

        /// <summary>
        /// The Date Time when the rating was given
        /// </summary>
        public DateTime TimeStamp { get; set; }

        /// <summary>
        /// The Order Id for which the Rating/Comments was given
        /// </summary>
        [Required]
        public int OrderId { get; set; }

        /// <summary>
        /// This is the Type of Rating Weather it is for the item or for the service
        /// </summary>
        public RatingType Type { get; set; }
    }
}